# Generated by Django 3.2.16 on 2023-01-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_vehicle_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='daily_max_rate',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='daily_min_rate',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='monthly_max_rate',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='monthly_min_rate',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
